spring:
  application:
    name: jpa

  ## DB Connection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: postgres

  ## JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
